package UI;

public enum PageId {
    LOGIN,
    REGISTER,
    APPLICANT_DASHBOARD,
    MORE_JOBS,
    RESUME_DATABASE,
    JOB_DETAIL,
    MESSAGES,
    INTERVIEW_INVITATION,
    MO_DASHBOARD,
    POST_VACANCIES,
    JOB_MANAGEMENT,
    APPLICATION_REVIEW,
    ADMIN_DASHBOARD
}
